---
title: "Class11: Structural Bioinformatics 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1. The PDB

Q1.  Determine the percentage of structures solved by X-Ray and Electron Microscopy. What proportion of structures are protein

```{r}
stats <- read.csv("Data Export Summary.csv",row.names=1)
stats
```

```{r}
#pct_xray <- stats[1,"Proteins"]/stats[,"Total"]
#pct_ele <- stats[3,"Proteins"]/stats[3,"Total"]
#print(pct_xray)
#pct_ele
#answer
pct.by.method <- stats$Total/sum(stats$Total)*100
names(pct.by.method) <- rownames(stats)
pct.by.method
```
```{r}
sum(stats$Proteins)/sum(stats$Total)*100
```
```{r}
library(bio3d)
```

```{r}
lbio3d()
```
```{r}
pdb <- read.pdb("1hsg")
pdb
```
```{r}
pdb$atom
```

```{r}
aa321(pdb$atom$resid)
```

```{r}
# Select all C-alpha atoms (return their indices)( 
ca.inds <- atom.select(pdb, "calpha")
ca.inds
# Select chain A( 
a.inds <- atom.select(pdb, chain="A")
# Select C-alphas of chain A( 
ca.inds <- atom.select(pdb, "calpha", chain="A")
# We can combine multiple selection criteria to return their intersection( 
cab.inds <- atom.select(pdb, elety=c("CA","CB"), chain="A", resno=10:20)
cab.inds
```
```{r}
 prot.inds<-atom.select(pdb,"protein")
prot.pdb<-trim.pdb(pdb,prot.inds)
write.pdb(prot.pdb,file="protein.pdb")
```

```{r}
lig.inds <-atom.select(pdb,"ligand")
lig.pdb <- trim.pdb(pdb,lig.inds)
write.pdb(lig.pdb,file="ligand.pdb")
```

```{r}
library("bio3d.view")
pdb <- read.pdb("5p21")
view(pdb)
```




