---
title: "class08"
author: "Yushan LIU"
date: "February 5, 2019"
output: html_document
---

Try k-value
```{r}
# Generate some example data for clustering 
tmp <- c(rnorm(30,-3), rnorm(30,3)) 
x <- cbind(x=tmp, y=rev(tmp)) 
plot(x)
#Run K-value
km<-kmeans(x, centers=2, nstart=20)
```
```{r}
km$cluster
plot(x,col=km$cluster)
points(km$centers,col='blue',pch=15,cex=2)
km$totss
```
Hierarchical clustering in R 
```{r}
# First we need to calculate point (dis)similarity 
#   as the Euclidean distance between observations 
dist_matrix <- dist(x) 
# The hclust() function returns a hierarchical 
#  clustering model 
hc <- hclust(d = dist_matrix) 
# the print method is not so useful here 
hc
```

```{r}
dim(dist_matrix)
View( as.matrix(dist_matrix) ) 
dim(x)
dim( as.matrix(dist_matrix) ) 
```


```{r}
plot(hc)
abline(h=6, col="red")
cutree(hc, h=6) # Cut by height h
#We can also use k=number of cluster group I want with **cuttree**
cutree(hc, k=2) 
```


```{r}
# Using different hierarchical clustering methods 
d<-dist_matrix
hc.complete <- hclust(d, method="complete") 
hc.average  <- hclust(d, method="average") 
hc.single   <- hclust(d, method="single")
plot(hc.single)
```

My turn 
```{r}
# Step 1. Generate some example data for clustering 
x <- rbind(  matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2),# c1  
             matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
             matrix(c(rnorm(50, mean = 1, sd = 0.3),           # c3 
             rnorm(50, mean = 0, sd = 0.3)), ncol = 2)) 
colnames(x) <- c("x", "y") 
# Step 2. Plot the data without clustering 
plot(x) 
# Step 3. Generate colors for known clusters 
#         (just so we can compare to hclust results) 
col <- as.factor( rep(c("c1","c2","c3"), each=50) ) 
plot(x, col=col) 
```
Q. Use the dist(), hclust(), plot() and cutree()      functions to return 2 and 3 clusters 
Q. How does this compare to your known 'col' groups?
```{r}
dist_matrix <- dist(x) 
hc2 <- hclust(d = dist_matrix)
print("hc")
hc2
plot(hc2)
abline(h=2,col="red")
abline(h=2.5,col="blue")
print("K=2")
g1<-cutree(hc2, k=2)
print("K=3")
g2<-cutree(hc2, k=3)
plot(x,col=g1)
plot(x,col=g2)

```
```{r}
plot(hclust(dist(x)))
```


PCA in R
```{r}
## You can also download this file from the class website! 
mydata <- read.csv("https://tinyurl.com/expression-CSV",row.names=1) 
head(mydata) 

```

```{r}
## lets do PCA 
pca <- prcomp(t(mydata), scale=TRUE) 
```

```{r}
## See what is returned by the prcomp() function 
attributes(pca) 
```

```{r}
## A basic PC1 vs PC2 2-D plot 
plot(pca$x[,1], pca$x[,2]) 
## Variance captured per PC  
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var.per 
barplot(pca.var.per, main="Scree Plot",          
        xlab="Principal Component", ylab="Percent Variation") 
```
```{r}
## A vector of colors for wt and ko samples 
colvec <- colnames(mydata) 
colvec[grep("wt", colvec)] <- "red" 
colvec[grep("ko", colvec)] <- "blue" 
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,      
     xlab=paste0("PC1 (", pca.var.per[1], "%)"),      
     ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
## Click to identify which sample is which 
identify(pca$x[,1], pca$x[,2], labels=colnames(mydata)) 
```


Try-on
```{r}
data <- read.csv("UK_foods.csv")
```

```{r}
#150
dim(data)
ncol(data)
nrow(data) 
```

```{r}
## Preview the first 6 rows
head(data)
View(data)
```
```{r}
# Note how the minus indexing works
rownames(data) <- data[,1]
data <- data[,-1]
head(data)
dim(data)
```
```{r}
barplot(as.matrix(data), beside=T, col=rainbow(nrow(data)))
```

```{r}
pairs(data, col=rainbow(10), pch=16)
```

```{r}
pca <- prcomp( t(data) )
summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
text(pca$x[,1], pca$x[,2], colnames(data),col=c("orange","red","blue","darkgreen"))
```

This will help us determines how th original variables (dimensions) contribute to our new PCs
```{r}
## Lets focus on PC1 as it accounts for > 90% of variance 
par(mar=c(10, 3, 0.35, 0))
barplot( pca$rotation[,1], las=2 )
```









