---
title: "Untitled07"
author: "Yushan LIU"
date: "January 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Function revist
```{r}
source("http://tinyurl.com/rescale-R")
```

Lets try the rescale()
```{r}
rescale(c(1,5,10))
```

Lets try **rescale2()** with the **stop** 



```{r}
x<-c(3,7,NA,4,8,NA)

which(is.na(x))
```
```{r}
x<-c(1,2,NA,3,NA)
y<-c(NA,3,NA,3,4)
```

```{r}
is.na(x)
sum(is.na(x))
is.na(x) & is.na(y)
```
```{r}
x <-  c(NA, NA, NA) 
y1 <- c( 1, NA, NA) 
y2 <- c( 1, NA, NA, NA)
y3 <- c( 1, NA, NA, NA,NA)
```

```{r}
both_na(x, y1)
```
```{r}
both_na(x, y2)
```
```{r}
both_na(x, y2)
```
```{r}
both_na3(x,y1)
```
```{r}
library(bio3d)
```


#' Analysis of input protein drug interactions by reading in any protein PDB data
#' @input a string containing the name of the PDB file to be read
#' @output a line plot analysis of input protein drug interactions
```{r}
 analysis_plot <- function(protein){
 s <- read.pdb(protein)
 s.chainA <- trim.pdb(s, chain="A", elety="CA") 
 s.b <- s.chainA$atom$b 
 plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor") 
}
```

```{r}
analysis_plot("4AKE")
```















